export const amazonFoods = [
  {
    "asin": "B0CKMR4T9P",
    "product_title": "肯德基单人套餐 - 原味鸡腿堡+薯条+可乐",
    "product_price": "¥39.90",
    "product_original_price": "¥45.00",
    "currency": "CNY",
    "product_star_rating": "4.7",
    "product_num_ratings": 2845,
    "product_url": "https://www.takeout.com/kfc/combo1",
    "product_photo": "https://demo.amazon-a.ws/food-kfc.png",
    "product_num_offers": 3,
    "product_minimum_offer_price": "¥35.90",
    "is_best_seller": true,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "5K+ bought in past month",
    "delivery": "预计送达时间 30分钟",
    "has_variations": true
  },
  {
    "asin": "B0CKLP7M2R",
    "product_title": "黄焖鸡米饭单人套餐 - 微辣口味+蔬菜+饮料",
    "product_price": "¥28.80",
    "product_original_price": "¥32.00",
    "currency": "CNY",
    "product_star_rating": "4.5",
    "product_num_ratings": 1967,
    "product_url": "https://www.takeout.com/huangmenji/single",
    "product_photo": "https://demo.amazon-a.ws/food-h.png",
    "product_num_offers": 2,
    "product_minimum_offer_price": "¥25.80",
    "is_best_seller": true,
    "is_amazon_choice": true,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "3K+ bought in past month",
    "delivery": "预计送达时间 25分钟",
    "has_variations": true
  },
  {
    "asin": "B0CKMN9F3L",
    "product_title": "必胜客双人比萨套餐 - 9寸披萨+烤翅+饮料",
    "product_price": "¥99.00",
    "product_original_price": "¥129.00",
    "currency": "CNY",
    "product_star_rating": "4.6",
    "product_num_ratings": 3278,
    "product_url": "https://www.takeout.com/pizzahut/double",
    "product_photo": "https://demo.amazon-a.ws/food-b.png",
    "product_num_offers": 4,
    "product_minimum_offer_price": "¥89.00",
    "is_best_seller": false,
    "is_amazon_choice": true,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "2K+ bought in past month",
    "delivery": "预计送达时间 40分钟",
    "has_variations": true
  },
  {
    "asin": "B0CKLR8T6P",
    "product_title": "麦当劳超值全家桶 - 汉堡+鸡翅+薯条+饮料",
    "product_price": "¥119.00",
    "product_original_price": "¥149.00",
    "currency": "CNY",
    "product_star_rating": "4.8",
    "product_num_ratings": 4532,
    "product_url": "https://www.takeout.com/mcdonalds/family",
    "product_photo": "https://demo.amazon-a.ws/food-m.png",
    "product_num_offers": 5,
    "product_minimum_offer_price": "¥109.00",
    "is_best_seller": true,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "6K+ bought in past month",
    "delivery": "预计送达时间 35分钟",
    "has_variations": true
  }
]
export const amazonProducts = [
  {
    "asin": "B0CTW8TXGH",
    "product_title": "Tracfone | Motorola Moto g Play 2024 | Locked | 64GB | 5000mAh Battery | 50MP Quad Pixel Camera | 6.5-in. HD+ 90Hz Display | Sapphire Blue",
    "product_price": "$39.88",
    "product_original_price": "$49.99",
    "currency": "USD",
    "product_star_rating": "4.4",
    "product_num_ratings": 232,
    "product_url": "https://www.amazon.com/dp/B0CTW8TXGH",
    "product_photo": "https://m.media-amazon.com/images/I/71CxUvG46rL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 1,
    "product_minimum_offer_price": "$39.88",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "3K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": false
  },
  {
    "asin": "B0CYQ916ZY",
    "product_title": "Google Pixel 8a - Unlocked Android Phone with Google AI, Advanced Pixel Camera and 24-Hour Battery - Obsidian - 128 GB",
    "product_price": "$399.00",
    "product_original_price": "$499.00",
    "currency": "USD",
    "product_star_rating": "4.3",
    "product_num_ratings": 879,
    "product_url": "https://www.amazon.com/dp/B0CYQ916ZY",
    "product_photo": "https://m.media-amazon.com/images/I/71n1Bn04lJL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 5,
    "product_minimum_offer_price": "$339.97",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": true,
    "sales_volume": "2K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": true,
    "product_badge": "Limited time deal"
  },
  {
    "asin": "B0DHSV6LCN",
    "product_title": "Samsung Galaxy Z Flip 6 AI Cell Phone, 512GB Unlocked Android Smartphone - (Renewed) (Blue, 512GB) (Blue)",
    "product_price": "$939.00",
    "product_original_price": null,
    "currency": "USD",
    "product_star_rating": "3.9",
    "product_num_ratings": 5,
    "product_url": "https://www.amazon.com/dp/B0DHSV6LCN",
    "product_photo": "https://m.media-amazon.com/images/I/51mRtvBdsqL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 1,
    "product_minimum_offer_price": "$939.00",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": false,
    "climate_pledge_friendly": false,
    "sales_volume": null,
    "delivery": "FREE delivery",
    "has_variations": true
  },
  {
    "asin": "B0CWHXVLXG",
    "product_title": "Moto G 5G | 2024 | Unlocked | Made for US 4/128GB | 50MP Camera | Sage Green",
    "product_price": "$149.99",
    "product_original_price": "$199.99",
    "currency": "USD",
    "product_star_rating": "4.2",
    "product_num_ratings": 1382,
    "product_url": "https://www.amazon.com/dp/B0CWHXVLXG",
    "product_photo": "https://m.media-amazon.com/images/I/71Sbx9zQN3L._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 3,
    "product_minimum_offer_price": "$109.80",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "3K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": true
  },
  {
    "asin": "B0CSB22F9C",
    "product_title": "Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
    "product_price": "$164.99",
    "product_original_price": null,
    "currency": "USD",
    "product_star_rating": "4.2",
    "product_num_ratings": 1419,
    "product_url": "https://www.amazon.com/dp/B0CSB22F9C",
    "product_photo": "https://m.media-amazon.com/images/I/51rp0nqaPoL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 11,
    "product_minimum_offer_price": "$139.00",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "4K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": false
  },
  {
    "asin": "B0CP6DDN1H",
    "product_title": "Moto G Play | 2024 | Unlocked | Made for US 4/64GB | 50MP Camera | Sapphire Blue",
    "product_price": "$109.99",
    "product_original_price": "$149.99",
    "currency": "USD",
    "product_star_rating": "4",
    "product_num_ratings": 1801,
    "product_url": "https://www.amazon.com/dp/B0CP6DDN1H",
    "product_photo": "https://m.media-amazon.com/images/I/61xk4XNRktL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 3,
    "product_minimum_offer_price": "$88.00",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "3K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": true
  },
  {
    "asin": "B0D7HV2PC9",
    "product_title": "Google Pixel 9 - Unlocked Android Smartphone with Gemini, 24-Hour Battery, Advanced Camera, and 6.3&quot; Actua Display - Peony - 128 GB",
    "product_price": "$649.00",
    "product_original_price": "$799.00",
    "currency": "USD",
    "product_star_rating": "4.5",
    "product_num_ratings": 230,
    "product_url": "https://www.amazon.com/dp/B0D7HV2PC9",
    "product_photo": "https://m.media-amazon.com/images/I/71xYvFHoSuL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 3,
    "product_minimum_offer_price": "$615.37",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "100+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": true
  },
  {
    "asin": "B086QCGQ8C",
    "product_title": "AT&amp;T BL102-3 DECT 6.0 3-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black",
    "product_price": "$68.95",
    "product_original_price": "$78.95",
    "currency": "USD",
    "product_star_rating": "4.3",
    "product_num_ratings": 28209,
    "product_url": "https://www.amazon.com/dp/B086QCGQ8C",
    "product_photo": "https://m.media-amazon.com/images/I/81xDumBYGBL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 5,
    "product_minimum_offer_price": "$35.58",
    "is_best_seller": true,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "3K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": false,
    "product_badge": "Best Seller"
  },
  {
    "asin": "B0BZG14KFJ",
    "product_title": "Panasonic Cordless Phone with Answering Machine, Advanced Call Block, Bilingual Caller ID and Easy to Read High-Contrast Display, Expandable System with 2 Handsets - KX-TGD832M (Metallic Black)",
    "product_price": "$59.99",
    "product_original_price": null,
    "currency": "USD",
    "product_star_rating": "4.3",
    "product_num_ratings": 4868,
    "product_url": "https://www.amazon.com/dp/B0BZG14KFJ",
    "product_photo": "https://m.media-amazon.com/images/I/81nkYlfA5ZL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 3,
    "product_minimum_offer_price": "$22.22",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "5K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": false
  },
  {
    "asin": "B0CRWT7WF1",
    "product_title": "Samsung Galaxy A05 A055M 64GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Black",
    "product_price": "$90.56",
    "product_original_price": null,
    "currency": "USD",
    "product_star_rating": "4.2",
    "product_num_ratings": 345,
    "product_url": "https://www.amazon.com/dp/B0CRWT7WF1",
    "product_photo": "https://m.media-amazon.com/images/I/61UjBLFlH2L._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 15,
    "product_minimum_offer_price": "$89.97",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "1K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": true
  },
  {
    "asin": "B0DLHNWHRF",
    "product_title": "SAMSUNG Galaxy A16 5G A Series Cell Phone, Unlocked Android Smartphone, Large AMOLED Display, Durable Design, Super Fast Charging, Expandable Storage, US Version, 2025, Blue Black",
    "product_price": "$199.99",
    "product_original_price": null,
    "currency": "USD",
    "product_star_rating": "3.9",
    "product_num_ratings": 22,
    "product_url": "https://www.amazon.com/dp/B0DLHNWHRF",
    "product_photo": "https://m.media-amazon.com/images/I/71KGkQ+KOKL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 1,
    "product_minimum_offer_price": "$199.99",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "500+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": true
  },
  {
    "asin": "B0C1Q3MVBP",
    "product_title": "Samsung Galaxy A14 5G A Series, Factory Unlocked, 64GB, US Version, Black (Renewed)",
    "product_price": "$98.33",
    "product_original_price": "$168.00",
    "currency": "USD",
    "product_star_rating": "3.7",
    "product_num_ratings": 1031,
    "product_url": "https://www.amazon.com/dp/B0C1Q3MVBP",
    "product_photo": "https://m.media-amazon.com/images/I/71L1ezoIH9L._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 24,
    "product_minimum_offer_price": "$77.00",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "2K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": false
  },
  {
    "asin": "B09SM24S8C",
    "product_title": "Samsung Galaxy A03s Cell Phone, AT&amp;T GSM Unlocked Android Smartphone, 32GB, Long Lasting Battery, Expandable Storage, 3 Camera Lenses, Infinite Display - Black (Renewed)",
    "product_price": "$70.00",
    "product_original_price": "$99.99",
    "currency": "USD",
    "product_star_rating": "3.8",
    "product_num_ratings": 918,
    "product_url": "https://www.amazon.com/dp/B09SM24S8C",
    "product_photo": "https://m.media-amazon.com/images/I/51m45B3Yy+L._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 18,
    "product_minimum_offer_price": "$59.00",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "1K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": true
  },
  {
    "asin": "B0CJCTW1C5",
    "product_title": "Nokia C2 2E | Android 11 (Go Edition) | Unlocked Smartphone | All Day Battery | 2/32GB | 5.7-Inch Screen | International Version | Blue",
    "product_price": "$59.99",
    "product_original_price": null,
    "currency": "USD",
    "product_star_rating": "3.3",
    "product_num_ratings": 207,
    "product_url": "https://www.amazon.com/dp/B0CJCTW1C5",
    "product_photo": "https://m.media-amazon.com/images/I/71PGVVHz08L._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 2,
    "product_minimum_offer_price": "$52.79",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "climate_pledge_friendly": false,
    "sales_volume": "1K+ bought in past month",
    "delivery": "FREE delivery Fri, Jan 24 Or fastest delivery Tue, Jan 21",
    "has_variations": false
  },
  {
    "asin": "B09VD33WHW",
    "product_title": "SAMSUNG Galaxy S22 Ultra 5G, US Version, 128GB, Black - Unlocked (Renewed)",
    "product_price": "$389.99",
    "product_original_price": null,
    "currency": "USD",
    "product_star_rating": "3.8",
    "product_num_ratings": 4773,
    "product_url": "https://www.amazon.com/dp/B09VD33WHW",
    "product_photo": "https://m.media-amazon.com/images/I/613Fp7fknhL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 20,
    "product_minimum_offer_price": "$327.99",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": false,
    "climate_pledge_friendly": false,
    "sales_volume": "1K+ bought in past month",
    "delivery": "FREE delivery Thu, Jan 23 Or fastest delivery Wed, Jan 22",
    "has_variations": true
  },
  {
    "asin": "B09LNW3CY2",
    "product_title": "Apple iPhone 13, 128GB, Midnight - Unlocked (Renewed)",
    "product_price": "$352.00",
    "product_original_price": "$392.20",
    "currency": "USD",
    "product_star_rating": "4.1",
    "product_num_ratings": 13919,
    "product_url": "https://www.amazon.com/dp/B09LNW3CY2",
    "product_photo": "https://m.media-amazon.com/images/I/61VuVU94RnL._AC_UY654_FMwebp_QL65_.jpg",
    "product_num_offers": 54,
    "product_minimum_offer_price": "$295.19",
    "is_best_seller": false,
    "is_amazon_choice": false,
    "is_prime": true,
    "product_availability": "Only 4 left in stock - order soon.",
    "climate_pledge_friendly": true,
    "sales_volume": "2K+ bought in past month",
    "delivery": "FREE delivery Wed, Jan 22 Only 4 left in stock - order soon.",
    "has_variations": true
  }
]
