import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 在 app/layout.js 中 (App Router)
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {children}
        <Toaster
            position="center" // 居中显示
            toastOptions={{
                // 自定义样式
                style: {
                    background: '#333',
                    color: '#fff',
                    padding: '16px 24px',
                    fontSize: '16px',
                    maxWidth: '400px',
                    width: 'auto',
                    textAlign: 'center',
                    borderRadius: '8px',
                    boxShadow: '0 4px 12px rgba(0,0,0,0.15)'
                },
                // 成功提示的自定义样式
                success: {
                    iconTheme: {
                        primary: '#10B981',
                        secondary: '#fff',
                    },
                }
            }}
        />
        </body>
        </html>
    );
}